### ISSUE TITLE
GWT Compile Shortcut - not focused on project root bug

### ISSUE THREAD

**Issue by branflake2267** [gwt-eclipse-plugin/gwt-eclipse-plugin#54]
When not focused on the root of the project tree, there was an exception.

```
------
STATUS
------
pluginId            org.eclipse.ui
pluginVersion       3.107.0.v20150423-1329
code                0
severity            4
message             Unhandled event loop exception
fingerprint         7f399f81

Exception:org.eclipse.e4.core.di.InjectionException: java.lang.ClassCastException: org.eclipse.jface.text.TextSelection cannot be cast to org.eclipse.jface.viewers.IStructuredSelection
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	 at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	 at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1504)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1293)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.dropdownEvent(HandledContributionItem.java:718)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:661)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1504)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1293)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:483)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.ClassCastException: org.eclipse.jface.text.TextSelection cannot be cast to org.eclipse.jface.viewers.IStructuredSelection
	 at com.google.gwt.eclipse.core.actions.GWTCompileToolbarHandler.execute(GWTCompileToolbarHandler.java:69)
	 at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	 at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:483)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	 at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	 at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1504)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1293)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.dropdownEvent(HandledContributionItem.java:718)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:661)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1504)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1293)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:483)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

------
REPORT
------
anonymousId         7689a93d-d258-431c-b536-d31ae368c2c5
name                Brandon Donnelson
email               branflake2267@gmail.com
comment             
eclipseBuildId      4.5.0.I20150430-1445
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0-ea-b123
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.10.3
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                com.google.gwt.eclipse.core
version             0.0.0.201505101348

name                org.eclipse.core.commands
version             3.7.0.v20150422-0725

name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.runtime
version             3.11.0.v20150405-1723

name                org.eclipse.e4.core.commands
version             0.11.0.v20150422-0725

name                org.eclipse.e4.core.contexts
version             1.4.0.v20150421-2214

name                org.eclipse.e4.core.di
version             1.5.0.v20150421-2214

name                org.eclipse.e4.ui.workbench
version             1.3.0.v20150429-1329

name                org.eclipse.e4.ui.workbench.renderers.swt
version             0.13.0.v20150428-1951

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150422-0725

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150423-1351

name                org.eclipse.swt
version             3.104.0.v20150430-1253

name                org.eclipse.ui
version             3.107.0.v20150423-1329

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150429-0914


```

**Comment by branflake2267** [comment]
I can't figure out how I did this, closing until I see it again.
